INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('005930', '삼성전자', 'KOSPI', '반도체', '💾');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('000660', 'SK하이닉스', 'KOSPI', '반도체', '💾');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('207940', '삼성바이오로직스', 'KOSPI', '제약/바이오', '💊');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('373220', 'LG에너지솔루션', 'KOSPI', '전기차 배터리', '🔋');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('105560', 'KB금융', 'KOSPI', '금융', '💰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('051910', 'LG화학', 'KOSPI', '화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('006400', '삼성SDI', 'KOSPI', '전기전자', '🔌');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('033780', 'KT&G', 'KOSPI', '담배', '🚬');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('003550', 'LG', 'KOSPI', '가전제품', '📺');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('012330', '현대모비스', 'KOSPI', '자동차부품', '🚗');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('017670', 'SK텔레콤', 'KOSPI', '통신', '📡');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('090430', '아모레퍼시픽', 'KOSPI', '화장품', '💄');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('009830', '한화솔루션', 'KOSPI', '화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('012450', '한화에어로스페이스', 'KOSPI', '항공우주', '🛩️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('010140', '삼성중공업', 'KOSPI', '조선해양', '🚢');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('088350', '한화생명', 'KOSPI', '보험', '🤝');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('034020', '두산에너빌리티', 'KOSPI', '에너지', '⚡');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('003490', '대한항공', 'KOSPI', '항공 운송', '✈️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('028260', '삼성물산', 'KOSPI', '패션/의류', '👕');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('066570', 'LG전자', 'KOSPI', '가전제품', '📺');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('009150', '삼성전기', 'KOSPI', '전자제품', '📱');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('096770', 'SK이노베이션', 'KOSPI', '에너지', '⚡');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('024110', '기업은행', 'KOSPI', '금융', '💰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('316140', '우리금융지주', 'KOSPI', '금융', '💰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('011200', 'HMM', 'KOSPI', '해운 및 물류', '🚢');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('010130', '고려아연', 'KOSPI', '금속', '🪙');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('055550', '신한지주', 'KOSPI', '금융', '💰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('030200', 'KT', 'KOSPI', '통신', '📡');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('011170', '롯데케미칼', 'KOSPI', '화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('004990', '롯데지주', 'KOSPI', '다각화', '🌐');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('336260', '두산퓨얼셀', 'KOSPI', '에너지', '⚡');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('029780', '삼성카드', 'KOSPI', '금융', '💰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('000120', 'CJ대한통운', 'KOSPI', '물류', '📦');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('000720', '현대건설', 'KOSPI', '건설', '🏗️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('086280', '현대글로비스', 'KOSPI', '물류', '📦');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('002380', 'KCC', 'KOSPI', '화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('004020', '현대제철', 'KOSPI', '철강', '🏗️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('011790', 'SKC', 'KOSPI', '화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('006360', 'GS건설', 'KOSPI', '건설', '🏗️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('036570', '엔씨소프트', 'KOSPI', '게임 개발', '🎮');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('035250', '강원랜드', 'KOSPI', '카지노/레저', '🎰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('402340', 'SK스퀘어', 'KOSPI', 'IT', '🖥️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('018260', '삼성에스디에스', 'KOSPI', '전자제품', '💻');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('023530', '롯데쇼핑', 'KOSPI', '소매', '🛍️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('008770', '호텔신라', 'KOSPI', '호텔 및 관광', '🏨');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('069960', '현대백화점', 'KOSPI', '소매', '🛍️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('035760', 'CJ ENM', 'KOSPI', '미디어 및 엔터테인먼트', '🎥');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('139480', '이마트', 'KOSPI', '유통업', '🛒');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('010950', 'S-Oil', 'KOSPI', '석유화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('456040', 'OCI', 'KOSPI', '화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('375500', 'DL이앤씨', 'KOSPI', 'IT', '🖥️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('064350', '현대로템', 'KOSPI', '국방산업', '🛡️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('018880', '한온시스템', 'KOSPI', '에너지', '⚡');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('007070', 'GS리테일', 'KOSPI', '소매업', '🏪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('120110', '코오롱인더', 'KOSPI', '화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('011210', '현대위아', 'KOSPI', '자동차 부품', '🚗');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('000880', '한화', 'KOSPI', '다양한 산업 분야', '🌐');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('006650', '대한유화', 'KOSPI', '석유화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('001450', '현대해상', 'KOSPI', '보험', '🤝');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('180640', '한진칼', 'KOSPI', '항공/해운', '✈️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('004000', '롯데정밀화학', 'KOSPI', '화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('282330', 'BGF리테일', 'KOSPI', '소매업', '🏪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('112610', '씨에스윈드', 'KOSPI', '풍력 발전', '🌬️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('009240', '한샘', 'KOSPI', '가구', '🛋️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('047040', '대우건설', 'KOSPI', '건설', '🏗️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('161390', '한국타이어앤테크놀로지', 'KOSPI', '타이어 및 자동차 부품', '🚗');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('089860', '롯데렌탈', 'KOSPI', '렌탈', '🔑');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('008930', '한미사이언스', 'KOSPI', '제약', '💊');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('251270', '넷마블', 'KOSPI', '게임', '🎮');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('032830', '삼성생명', 'KOSPI', '보험', '🤝');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('028670', '팬오션', 'KOSPI', '해운 및 물류', '🚢');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('051900', 'LG생활건강', 'KOSPI', '건강/화장품', '🧴');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('016360', '삼성증권', 'KOSPI', '금융', '💰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('071050', '한국금융지주', 'KOSPI', '금융', '💰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('047810', '한국항공우주', 'KOSPI', '항공우주', '🛩️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('035720', '카카오', 'KOSPI', 'IT', '🖥️');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('086790', '하나금융지주', 'KOSPI', '금융', '💰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('005940', 'NH투자증권', 'KOSPI', '금융', '💰');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('078930', 'GS', 'KOSPI', '다양한 산업 분야에 걸쳐 다양한 사업을 영위하는 그룹사', '🌐');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('097950', 'CJ제일제당', 'KOSPI', '식품', '🍜');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('036460', '한국가스공사', 'KOSPI', '에너지', '⚡');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('005830', 'DB손해보험', 'KOSPI', '보험', '🤝');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('034730', 'SK', 'KOSPI', '다양한 산업에 걸쳐 활동하는 그룹사들을 보유한 다이버시파이드 산업군', '🌐');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('128940', '한미약품', 'KOSPI', '제약', '💊');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('035420', '네이버', 'KOSPI', '인터넷', '🌐');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('011780', '금호석유', 'KOSPI', '석유화학', '🧪');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('069500', 'KODEX200', 'KOSPI', '다양한 산업군을 포함한 종합주가지수', '📈');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('005380', '현대차', 'KOSPI', '자동차', '🚗');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('005490', '포스코홀딩스', 'KOSPI', '제조업', '🏭');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('015760', '한국전력', 'KOSPI', '전기공급', '💡');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('204320', '만도', 'KOSPI', '음식료품', '🍜');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('000150', '두산중공업', 'KOSPI', '조선', '🚢');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('010120', 'LS ELECTRIC', 'KOSPI', '전기 및 전기제품', '🔌');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('010620', '현대미포조선', 'KOSPI', '조선', '🚢');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('009540', '한국조선해양', 'KOSPI', '조선해양', '🚢');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('000810', '삼성화재', 'KOSPI', '보험', '🤝');
INSERT INTO stocks (symbol, name, market, sector, emoji) VALUES ('326030', 'SK바이오팜', 'KOSPI', '제약/바이오', '💊');