services:
  # Database Service (for local development)
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=hanazoom
      - MYSQL_USER=${DB_USERNAME:-hanazoom_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-hanazoom1234!}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-hanazoom1234!}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${DB_USERNAME:-hanazoom_user}",
          "-p${DB_PASSWORD:-hanazoom1234!}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network

  # Redis Service (for local development)
  redis:
    image: redis:7-alpine
    ports:
      - "16380:6379" # 포트 변경: 6379 → 6380
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis1234!}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis1234!}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
